# Document Service API Testing

# Create a New Document
POST http://localhost:5000/documents
Content-Type: application/json; charset=UTF-8

{
    "id": "some-unique-identifier1",
    "tags": ["important", ".net"],
    "data": {
        "some": "data",
        "optional": "fields"
    }
}

# Retrieve Document in Different Formats

# JSON
GET http://localhost:5000/documents/some-unique-identifier1
Accept: application/json

# XML
GET http://localhost:5000/documents/some-unique-identifier1
Accept: application/xml

# MessagePack
GET http://localhost:5000/documents/some-unique-identifier1
Accept: application/x-msgpack

# Update Document
PUT http://localhost:5000/documents/some-unique-identifier1
Content-Type: application/json

{
    "tags": ["updated", "important"],
    "data": {
        "some": "updated data",
        "new_field": "value"
    }
}

# Delete Document
DELETE http://localhost:5000/documents/some-unique-identifier1